### ISSUE TITLE
Won't Activate Plugin

### ISSUE THREAD

**Issue by trismegistis** [daemon/mcex-plugin#10]
Hi I try running the plugin but it doesnt generate the folder in the plugins or get listed with /plugin.

I don't have mysql running, but shouldn't it have made the folder first?

**Comment by daemon** [comment]
Do you have write permissions for the plugins folder? Yes, it should've made the folder first. Does the log say anything interesting?

**Comment by trismegistis** [comment]
No logs. I'm on kcauldron 1.7.10, and tried all available versions. Any libs?

**Comment by trismegistis** [comment]
Here you go:

[00:45:01] [Server thread/ERROR]: Could not load 'plugins\mcex-plugin-0.4.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `xyz.mcex.plugin.McexPlugin'
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:191) ~[PluginClassLoader.class:1.7.10-1492.152]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1492.152]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1492.152]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1492.152]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:1.7.10-1492.152]
    at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
    at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
    at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.ClassNotFoundException: Failed to remap class xyz.mcex.plugin.McexPlugin
    at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:1.7.10-1492.152]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-1492.152]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1492.152]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_65]
    at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-1492.152]
    ... 12 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
    at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
    at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
    at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:453) ~[PluginClassLoader.class:1.7.10-1492.152]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-1492.152]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1492.152]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_65]
    at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-1492.152]
    ... 12 more

**Comment by Siphonophore** [comment]
The plugin was explicitly designed for 1.8... not sure if it is compatible with KCauldron or 1.7.10.
