### ISSUE TITLE
Could not load 'plugins/mcex-plugin-0.4.1.jar' -  io/vertx/core/Verticle Error

### ISSUE THREAD

**Issue by ldath** [daemon/mcex-plugin#11]
When building

```
/home/ldath/mcex-plugin/src/main/xyz/mcex/plugin/equity/SellCommand.java:163: error: unmappable character for encoding UTF8
            ChatColor.GRAY + "�7%player " + ChatColor.GRAY + "is selling " + ChatColor.GOLD + "%quantity %item_name " + ChatColor.GRAY + "at " +
                              ^
/home/ldath/mcex-plugin/src/main/xyz/mcex/plugin/equity/BuyCommand.java:110: error: unmappable character for encoding UTF8
            ChatColor.GRAY + "�7%player " + ChatColor.GRAY + "wants " + ChatColor.GOLD + "%quantity %item_name " + ChatColor.GRAY + "at " +
                              ^
:processResources
:classes
:jar
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL
```

When trying to use create jar:

```
[21:29:17] [Server thread/ERROR]: Could not load 'plugins/mcex-plugin-0.4.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: io/vertx/core/Verticle
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.NoClassDefFoundError: io/vertx/core/Verticle
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_65]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: io.vertx.core.Verticle
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_65]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_65]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
    ... 6 more
```

Maybe I'm missing something?

**Comment by ldath** [comment]
Sorry - for this I need: 

```
gradle fatjar
```
